### PR TITLE
fix: clear & custom state properties and custom state typing

### LINKED ISSUE #85: Feature: Ability to delete an entity/entities from the store by id.
One feature (that seems would be somewhat easy to implement) that would be quite convenient, is the ability to remove entities from the store with only an id.  Currently in order to delete an entity or entities, I am doing the following:

```
  store$.dispatch(new DeleteSuccess(EntityType, entityToDelete));
  // or
  store$.dispatch(new DeleteManySuccess(EntityType, entitiesArray));
```

However, this requires that I already have the entity or entities I want to delete.  My problem there also goes back to my frequent use of child/parent relationships.  There are many times I'd like to delete, say, all of the children of a given parent, but in the current view I only have a list of child ids.  It would be great to be able to do something like:

```
  store$.dispatch(new DeleteIdSuccess(EntityType, entityIdToDelete));
  // or
  store$.dispatch(new DeleteManyIdsSuccess(EntityType, entityIdArray));
```

rather than having to go fetch an entity or entity array in order to remove.

### LINKED ISSUE #86: Clearing entity state eliminates any custom state the user may have added
**ISSUE:**

When clearing entity state, either by dispatching the `Clear` action or using the `clear()` facade method, the meta reducer currently replaces the entire state with a new version that reflects the default empty state of default entity state. This wipes out any custom state the developer may have added when using `buildState`:

```typescript
export const { initialState } = buildState(MyEntity, {
  customState: 'hello'
}

console.assert(initialState.customState === 'hello', 'Initial state is invalid!');
```

**EXPECTATION:**

The auto-entity meta reducer should preserve any custom developer state as-is in its current state when clearing entity state.

### LINKED ISSUE #88: Compiling projects using auto-entity under TS 3.x causes type errors when extra state is included
**ISSUE:**

When including custom state properties or "extra initial state" with the `buildState` and `buildFeatureState` functions, typescript will begin throwing type errors for certain use cases. A notable and common case is when defining the reducer for the state, which will cause type errors when you return the state if set to `initialState` that is destructured from `buildState` itself. 

```typescript
export const { initialState } = buildState(MyEntity, {
  customState: 'hello'
}

export interface IMyEntityState extends IEntityState<MyEntity> {
  customState: string;
}

export function myEntityReducer(state = initialState): IMyEntityState {
  return state; // Typescript throws type error here
}
```

**EXPECTATION:**

Auto-entities typing should be rich enough to support custom/extra state without causing any typing errors anywhere auto-entity state or related data/types may be referenced.

### PR DESCRIPTION
**Pull request by jrista**
* Updated clear reduction to spread existing state first to preserve custom state
 * Updated typings for all utility functions and types to ensure extra state types work with TS 3.x

Resolves: #85, #86, #88

### CODE REVIEW

File: projects/test-app/src/app/app.component.ts [hunk 1]
```diff
@@ -11,5 +11,6 @@ export class AppComponent {
 
   constructor(public customers: CustomerFacade) {
     customers.loadAll();
+    setTimeout(() => customers.clear(), 3000);
```
Comment (paquettealice) [inline projects/test-app/src/app/app.component.ts]: Should this line still be here or was it purely for testing?

File: projects/test-app/src/app/state/customer.state.ts [hunk 2]
```diff
@@ -1,7 +1,14 @@
 import { buildState, IEntityState } from '@briebug/ngrx-auto-entity';
 import { Customer } from '../models/customer.model';
 
-export const { initialState, facade: CustomerFacadeBase } = buildState(Customer);
-export function customerReducer(state = initialState): IEntityState<Customer> {
+export const { initialState, facade: CustomerFacadeBase } = buildState(Customer, {
+  customProperty: 'hello'
```
Comment (paquettealice) [inline projects/test-app/src/app/state/customer.state.ts]: Similar to the previous comment, was this purely for testing (or, in this case, perhaps it's to show custom properties can be used?)

**Comment by paquettealice** [comment]
Other than the two demo-related questions above, looks good to me.

File: projects/test-app/src/app/app.component.ts (hunk 1 above)
Comment (jrista) [reply projects/test-app/src/app/app.component.ts]: This is jus a test app. It is simpler than the demo app, and I've been using it just to play around with things in a real-world context. The timeout here was so that the clear action was dispatched after the load action was handled. Without the timeout, clear was being sent after Load but before LoadSuccess was dispatched.

Since it is just a test app, this code doesn't really matter. It'll also probably change in the future for testing different features. I also encourage you guys to use it, if you need to play with a feature! ;)

File: projects/test-app/src/app/state/customer.state.ts (hunk 2 above)
Comment (jrista) [reply projects/test-app/src/app/state/customer.state.ts]: Yup, purely for testing.

File: projects/test-app/src/app/app.component.ts (hunk 1 above)
Comment (paquettealice) [reply projects/test-app/src/app/app.component.ts]: Sorry, hadn't noticed it wasn't the demo app. Woops!

**Review by paquettealice — APPROVED** [review]
